### PR TITLE
Make transition labels stack on top of each other

### LINKED ISSUE #281: Transition label stacking
Currently when two states have multiple transitions between them, each transition is a seperate arrow. It would be ideal if the transitions all stacked onto one arrow. Self transitions already do this. Particularly important due to the amount of transitions that can be required between two states in Computing Theory assignments.

Current behaviour:
Screen Shot 2023-03-12 at 9 56 03 pm

Desired behaviour:
Screen Shot 2023-03-12 at 9 57 00 pm

Current behaviour of self transitions (reflects desired behaviour):
Screen Shot 2023-03-12 at 9 59 54 pm

### PR DESCRIPTION
**Pull request by ire4ever1190**
closes #281, #242

image

Transition labels are now stacked on top of each other instead of creating a new edge. This makes the behaviour be like JFLAP where the transitions labels are like a column that are aligned to the normal of the edge.

Selecting a transition can be done by just clicking the label, if you want to select all transitions then you can select the edge.

This also converts a few more files to typescript that I was interacting with

### CODE REVIEW

**Review by SidhraFernando-Plant — CHANGES_REQUESTED** [review]
sorry to be the spacing police again 🚨🚔🚨 but I feel there is a bit too much space now between the transitions and the labels (ie. transition arrow and first transition).

Screen Shot 2023-04-17 at 1 04 32 pm

 If possible, it would be good to reduce this spacing closer to what it was before. The spacing between the stacked transitions themselves is fine, though it would be fine to reduce this a bit if needed to bring the labels closer to the transition.

**Comment by SidhraFernando-Plant** [comment]
Everything else looks great though, and it works really smoothly 👌

**Comment by ire4ever1190** [comment]
All good, always feel free to be spacing police :muscle: 

Should be easy fix, will do :+1:

**Review by SidhraFernando-Plant — CHANGES_REQUESTED** [review]
Looking good for transitions between different states ⭐️ but the spacing for self-transitions is still at the larger value - it would be good to bring this down to the same as the other transitions


Screen Shot 2023-04-19 at 7 28 54 pm

**Comment by ire4ever1190** [comment]
image
The spacing has been changed and is a lot better now implementation wise. I now properly calculate the coordinate of the midpoint and then offset from that which is way less hacky than what I was doing before

**Review by SidhraFernando-Plant — APPROVED** [review]
Great job refining this solution 👍🏻

**Pull request merged**
