### PR TITLE
Support reordering graph states

### LINKED ISSUE #234: Reorder state IDs
Option to reorder state IDs based on the transition flow.

### PR DESCRIPTION
**Pull request by ire4ever1190**
Closes #234 

Adds ability to reorder states in the graph (Command is done via right click menu). This is done using a flood fill that goes breath first when there is multiple options but continues along states that have single transitions. This is done so that continuous transitions come one after another. The reason a topological sort wasn't chosen was because that wouldn't work with cycles

**Before**
image

**After** 
image

(Notice how the left side is in order)

The ordering isn't perfect in some cases (especially when the graph is spaghetti) but for most cases it works well.

### CODE REVIEW

**Comment by giraugh** [comment]
This looks so hype

**Comment by tdib** [comment]
Yeah this is spicy hot

**Comment by GRA0007** [comment]
Love this

**Review by LvandoApps — APPROVED** [review]
Looks sweet as

**Pull request merged**
