### PR TITLE
Remove the delete tool

### PR DESCRIPTION
**Pull request by ire4ever1190**
We decided that it wasn't a good idea to have the delete tool cause of UX (You can already right click)

### CODE REVIEW

**Review by tdib — CHANGES_REQUESTED** [review]
Should also remove the associated animation so there aren't any unnecessary files

**Review by GRA0007 — APPROVED** [review]
Keyboard shortcut dialog is broken?

**Review by tdib — CHANGES_REQUESTED** [review]
The keyboard shortcut "d" deselects any tools - the shortcut should also be removed :)

**Comment by ire4ever1190** [comment]
> Keyboard shortcut dialog is broken?

Separate issue, looking into it now

**Pull request merged**
