### PR TITLE
Implement view controls

### PR DESCRIPTION
**Pull request by giraugh**

### CODE REVIEW

**Review by tdib — APPROVED** [review]
This looks amazingly wonderful to me. Thank you for all your hard work in this implementation it is quite incredible, I love it very much. LGTM

**Comment by tdib** [comment]
Furthermore, this added functionality is extremely useful and definitely one of my favourite features in Automatarium thus far. Being able to zoom to fit is perhaps the most useful zoom functionality we have within this project and we would not have it without you. We would not even have SVG rendering without all the time and effort you have put into the project so thank you. Your work is absolutely stunning and I appreciate all that you have done for this project. Your hard work will not go unnoticed, keep it up <3

**Comment by tdib** [comment]
And to the user who implemented the backend - also absolutely incredible work. The backend is what makes our project... our project. The cloud functionalities provided will make the experience for future Computing Theory students far more streamlined and keep a clutter of files off our systems! I can't wait to create automata and send it to a friend to discuss with one another, or hopefully have the professor link the students to an automaton instead of having them download an entirely separate file!

**Comment by tdib** [comment]
To the individual who has put many hours into writing and organising our documentation and testing - we love and appreciate your work 😌 The painstaking effort of ethics documents and dealing with people for testing is something no one wants to do, although absolutely necessary, and one of the most important aspects of the project.

**Comment by tdib** [comment]
The design of Automatarium is incredible. Oh how I wish I could design with such tenacity and elegance. From a baby design on Figma all the way to the product at its current stage you have been on the front lines, leading our project in the best direction possible. Your hard work on aesthetics and accessibility will perhaps be the most noticed aspects of the project and I commend you for it.

**Comment by tdib** [comment]
And to all of you, collectively, I admire your hard work and efforts throughout this project. We are almost there and we will ace this! I look up to all of you as my mentors and would not be where I am today without you. Thank you.

**Comment by Prydeton** [comment]
dib kinda helped

**Comment by tdib** [comment]
lil bit

**Pull request merged**
