### PR TITLE
Update with files from last semester

### LINKED ISSUE #53: Execute a PDA
The simulation package should be able to simulate push-down automata

### PR DESCRIPTION
**Pull request by ire4ever1190**
Adds the last group's code into the repo

I got a [temporary deployment](https://admirable-salmiakki-2c1be2.netlify.app) if anyone is curious what the site is now like (No backend running currently, but seems no changes were made to it anyways)

From looking at the documents we were given the new features are
- Rewritten execution algorithm to use BFS instead of recursively solving
- Supports PDAs (Closes #53)
- Supports Turing machines (With tape lab to provide UI for stepping through execution)
- Deleting states and transitions

### CODE REVIEW

**Comment by ire4ever1190** [comment]
approve

**Comment by LvandoApps** [comment]
b8c

**Review by tdib — APPROVED** [review]
Dear [GitHub user],

I wanted to take a moment to thank you for your hard work and dedication in contributing to this project. Your code has been a valuable addition, and I truly appreciate the effort you have put into making it the best it can be.

In particular, I wanted to let you know that your pull request has received my LGTM (Looks Good To Me) approval. This means that I have thoroughly reviewed your code and have found it to be of excellent quality. Your attention to detail and commitment to writing clean, concise code is evident, and I have no doubt that it will greatly benefit this project.

As a developer myself, I understand the time and effort that goes into creating and reviewing code. Your contributions have not gone unnoticed, and I am grateful for the opportunity to work alongside you on this project.

I hope that this LGTM approval serves as a sign of my appreciation for your hard work and dedication. Your contributions have made a difference, and I look forward to seeing more of your excellent work in the future.

Thank you once again for your valuable contributions to this project.

Best regards,
[Your name]

**Comment by ire4ever1190** [comment]
A new age dawns🦕

**Pull request merged**
