### PR TITLE
Import machines from json and base64 encoded formats

### LINKED ISSUE #287: Have way to share project without backend
The backend is cool but setting up deployment is a bit annoying. Having a way to load a project from [pastebin](https://pastebin.com/) or [ixio](http://ix.io/) would make sharing projects (and reproducible examples for bugs) be a lot easier.

Example of the link https://automatarium.github.io/editor?project=DPX would load the `DPX` paste from [ixio](http://ix.io/)

There should also be a share button that automatically uploads the project and shows the link

### PR DESCRIPTION
**Pull request by anioncat**
Kinda closes #287. A new issue will be created for future development.

- Hijacked the `/share` endpoint for importing data that is base64 encoded
  - The share endpoint has to do with getting it from the backend, which doesn't exist
  - Endpoint is now `/share/:type/:data` where type has `raw` (switchable) and `data` is encoded in base64.
  - Currently has no issue with a relatively large machine, but short urls will be a future update
  - A URL from the PR deployment to try (updated with msgpack commit)
```
https://automatarium-frontend-jju18zbnp-automatarium.vercel.app/share/raw/H4sIAAAAAAAAA4WWS08UQRDH9wHLa3m_FgTF+MDXIqCG1RPRaDSRxCDxanpneqDNzjTMNKLxpAEPekET7izugohe9Bvo0RC8mvAN9At4MVbPw1DMdGYPe_jXb_5V1anqmVc78zZ_RDUx83SebsxMvXvI9J8nL+mF8fErxYl8UTdI_rJRLOYL+tVinhiFMTphTBiXxwqbjiCCOvuJI8vlJ7vJtfLT75PPryXkb4PpiS3m3GIWKX0NorvJFtCTB_Xvk8v77gNBNIWjr5+haFoZXYNoDcqYGgj02nAl6dugZ1SVuNE6VS43Wq+Kpn5AtCFcias3Ij2dlRX+Bb0prKdWQM9ifQ+fcDOK1hSkWwX0Fqy_DbK3Yv13wLchvVbHWdpRtG4BRzuC6Df32V+BZyd6KmMHehfW_wR6N67hV1BzT9jH1XvDPq6eC_Xi+feFdZfv_6_vCJtYDhOMWzDSIy8rhs3N5IbgKTm0FZsSvUyrSzYTtKxt68yGlQG2PO2RKSDTcoA9kqvJBJBJOcweaarJNJA1crA9cklN1gBZK0fdI4fUZK2fPRObXdaZkYuAs+thMgNknVwK3HsEWQdkvVyQWLIeyAa5Mh5pqMkGIBvlEuHeI8hGv6NsbEfylJrkirnkesQh3fXAJh9s8Sw1NSmTZ+UWIks9DGZ9sM2z1NWkTN4sVxQnvxPuJ+uTHdgzgmwGUl61ndhzWE12Yc8IsgXIVrnkmDTVZA_OHkG2AtkmLwJErqvBHEoeAbYB2C6vCpybqMl+3E8E2QlkF5ADsZ4BOYjGIwLsArAbwKPYUqjJY8gyAuz2waG4s5RgB4DHDzquhwezB7he4E7gA+Jhx4A8iWqMAHsBzAF4ClvOqsnTyDICzPngcNxk5Py2z8S03Q5cH3Bn485Rgv0AnovL3AdgJ4Dn1dfLIfKC8sbywX4AewDMq6+XQ+SI8sY69Pa5GJc7uKpH1Y7vNW6a1BLO6rbDzGnqLJbEahU+M4XzYtNh1myJbi9xbgzJv2qRCG3uzfpHZsGLm5Tuyw_SRMWkgqxULGLST_fAmPFFZ+g652JHh_ANSC2ovpdIJF9NDlp3P0jxps7+a1OD81uPqe1AOdWxkdGR0S9kUXCTCGKzRfPBwcimxi2DzS5XhPftvON+EUNOgz0pL3wmmkbnBbE0SAr+NiOVIhdzVY2XuF2dtSm1_gF9O6qgfgsAAA==
```
- Added an import dialog to facilitate
  - Importing from file on computer (old behaviour)
  - Importing from a URL that has raw text (such as a pastebin)
    - Here is a url to try
```
https://gist.githubusercontent.com/anioncat/baf0710a5247b159648f4542d1c24975/raw/5f2ef513e947320d8a6cb48908b4cd2923faddc5/Precious%2520Boot.json
```
- ...
  - Importing from the URL Automatarium gives you (in case you don't just want to put that in the address bar)
  - Importing from the encoded data (in case you also want to do that)
- Added an export dialog to facilitate
  - Providing the encoded data
  - Providing a link you can share with other people (it will be long)
- New menu items in `File -> Import -> Import other...` and `File -> Export -> Export as URL/Raw data...` for these functions from within the editor

Future to dos:
- Short URLs so people can copy them from the projector in a lecture/tutorial

### CODE REVIEW

**Comment by anioncat** [comment]
Update to add msgpack to shorten the json file. No idea why the PR action failed bu the push action and deployment succeeded.

**Review by S3865562 — APPROVED** [review]
This is great, it works really well :)
One minor observation: imported projects don't save unless modified, but I checked and realised this was existing behaviour. Potentially something we could consider for future improvements?

**Comment by anioncat** [comment]
Made it a now fix. Another one of those things I noticed but forgot to address about during development. There doesn't appear to be a way to force it to happen inside ProjectStore, such as committing nothing, so I've had to use ProjectsStore to add it in.

Can you just double check I didn't break anything?

**Comment by S3865562** [comment]
Oh nice. I'm not encountering any issues 👍

**Pull request merged**
