### PR TITLE
Enhance multiple inputs per transition

### LINKED ISSUE #412: Multiple inputs per transition
### Proposed feature or solution

It is very tedious to individually add every transition in a FSA.

Multiple transitions should be able to be added via comma separated values or similar.

### Alternatives

_No response_

### Additional information

(I know ranges exist somewhere so if this is already implemented then the issue is to document it for the users to know that they can use it.)

### PR DESCRIPTION
**Pull request by S3865562**
Closes #412 and #404 

- When a user enters a sequence of characters in the read field and presses enter, OR operators are inserted between each character ('abc' is now displayed as 'a | b | c')
- Enables multiple read inputs per transition for TMs, ensuring uniformity and consistency when working with different automata types
- Introduces a default OR operator which users can customise via the File Options menu
- Patches misaligned trace tape bubble

Screen Shot 2023-09-23 at 14 07 57

Screen Shot 2023-09-23 at 14 08 08

Currently working on a transition tutorial so people know about all of the unique things Automatarium can do with transitions.

### CODE REVIEW

**Comment by S3865562** [comment]
Unsure about including 'OR' as an option in the dropdown menu, definitely open to suggestions. 
Also going to prioritise increasing the margins between input fields for both TMs and PDAs, since with multiple inputs they can look especially cluttered.

**Comment by anioncat** [comment]
Yeah I'm not sure on OR since a user might be using those characters or even $\lor$ since it looks a bit like v. Might be a bit confusing.

**Comment by S3865562** [comment]
Have you experimented with it? At the moment, if the user enters 'v' but the ∨ operator is configured, the entered v is interpreted as ∨. So if they enter 'avb', it'll turn into 'a ∨ b'. I just figured if they want to use v in their input alphabet, they can just change the OR operator from the drop down. But if you think I should remove it, I'd be happy to.

I've used aliases for all of the symbols, another example is + and ＋.

**Comment by anioncat** [comment]
I hadn't had a play with it yet but I now see that it's greyed out so it's pretty clear that its not part of the language. Is removing the or operator on the PDA pop/push string intended? Otherwise looks good to me

**Review by anioncat — APPROVED** [review]

**Pull request merged**
